### ISSUE TITLE
Update Fix for, Define and throw a dedicated exception instead of using a generic one.

### ISSUE THREAD

**Issue by Anik131** [numanSlm/OpenTracks-Winter-SOEN-6431_2024#13]
![image](https://github.com/numanSlm/OpenTracks-Winter-SOEN-6431_2024/assets/58440210/19125452-fd6a-4c04-9c82-e3ffcfc75214)

Fixed Codes, 
![image](https://github.com/numanSlm/OpenTracks-Winter-SOEN-6431_2024/assets/58440210/1c15c06f-2623-41c4-b073-4007cfbacd67)
![image](https://github.com/numanSlm/OpenTracks-Winter-SOEN-6431_2024/assets/58440210/d2a0c84a-72de-4071-a6bc-f291ea51e9d9)

**Comment by nihal514** [comment]
Issue resolved.
Refer Commit : b444f08
