### ISSUE TITLE
Define and throw a dedicated exception instead of a generic one

### ISSUE THREAD

**Issue by ushnish2001** [numanSlm/OpenTracks-Winter-SOEN-6431_2024#18]
**Technical Debt Problem Statement** : Define and throw a dedicated exception instead of a generic one

![Screenshot 2024-02-16 at 4 45 59 PM](https://github.com/numanSlm/OpenTracks-Winter-SOEN-6431_2024/assets/60659214/eba65069-55f9-4d44-ae9e-812039757f96)

**corrected code :** 

  @Nullable
    public static Intent newShareFileIntent(Context context, Marker.Id... markerIds) {
        if (markerIds.length == 0) {
            throw new ShareUtilsException("Need to share at least one marker.");
        }

        String mime = null;

        ContentProviderUtils contentProviderUtils = new ContentProviderUtils(context);
        ArrayList<Uri> uris = new ArrayList<>();
        
        boolean shouldbreak = false;
        for (Marker.Id markerId : markerIds) {
            Marker marker = contentProviderUtils.getMarker(markerId);
            if (marker == null) {
                Log.e(TAG, "MarkerId " + markerId.id() + " could not be resolved.");
                shouldbreak = true;
            }
            else if (marker.getPhotoURI() == null) {
                Log.e(TAG, "MarkerId " + markerId.id() + " has no picture.");
                shouldbreak = true;
            }
            else{
                mime = context.getContentResolver().getType(marker.getPhotoURI());
                uris.add(marker.getPhotoURI());
            }

            if(shouldbreak){
                shouldbreak = false;
                continue;
            }
        }

        if (uris.isEmpty()) {
            return null;
        }

     
        return new Intent(Intent.ACTION_SEND_MULTIPLE)
                .setType(mime != null ? mime : "image/*")
                .putParcelableArrayListExtra(Intent.EXTRA_STREAM, uris)
                .addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
                .putExtra(Intent.EXTRA_SUBJECT, context.getString(R.string.share_image_subject))
                .putExtra(Intent.EXTRA_TEXT, context.getString(R.string.share_image_body));
    }

**Comment by nihal514** [comment]
Issue resolved.
Refer Commit : 9195a69
