### ISSUE TITLE
Update local variable as per coding convention

### ISSUE THREAD

**Issue by YugKotak** [numanSlm/OpenTracks-Winter-SOEN-6431_2024#6]
Code smell:
![Screenshot 2024-02-16 010335](https://github.com/numanSlm/OpenTracks-Winter-SOEN-6431_2024/assets/145585091/7f1b7f61-f735-44ab-937d-0ebd9b9ad95a)

Fixed code:
![Screenshot 2024-02-16 010717](https://github.com/numanSlm/OpenTracks-Winter-SOEN-6431_2024/assets/145585091/5032ee56-5f25-4d73-b789-2b28c45027f5)

**Comment by nihal514** [comment]
Issue resolved.
Refer Commit : b8b9f9d
